name = "emailer"
main = "src/index.ts"
compatibility_date = "2023-09-22"

[[kv_namespaces]]
binding = "NEWS_LETTER_KV"
id = "acc7679be0c345cebd7a1345d52abcf8"
preview_id = "d366f54af4bb45838291d9055e564bc7"

[vars]
FROM = "No Reply <no-reply@newsletter.timsexperiments.foo>"
VALID_API_KEY = "ackabulucka"
RESEND_API_KEY = "re_A2PnHL1o_5oAtoNqpWxDZ3vZxkXkgh9F9"
